/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import { TestType } from '../../../types';

declare module 'zapatos/custom' {
  export type PgGeometry = TestType;
}
